### ISSUE TITLE
nnUNetPlansv2.1_plans_2D.pkl file has not been created under data_pro/nnUNet_preprocessed/Task027_ACDC

### ISSUE THREAD

**Issue by greenyjwk** [innocence0206/UCTNet#2]
Hello,

I am glad to reach out to you.

while I was preprocessing the ACDC dataset, I used the following command for the dataset preprocessing.
`UCTNet_ACDC -dataset_path DATASET_PATH`
I expected that it would create the nnUNetPlansv2.1_plans_2D.pkl file under the data_pro/nnUNet_preprocessed/Task027_ACDC, but the file hasn't been created.

I have faced the following error.
`FileNotFoundError: [Errno 2] No such file or directory: '../home/gxy/data_pro/nnUNet_preprocessed/Task027_ACDC/nnUNetPlansv2.1_plans_2D.pkl'`

For your reference, from the code at line number 32 to 34 at UCTNet/nnUNet/nnunet/paths.py", I have created my own directory such as 
```
base = "/myown_root_dir/gxy/dataset/nnUNet_raw_data_base"
preprocessing_output_dir = "/myown_root_dir//gxy/data_pro/nnUNet_preprocessed"
network_training_output_dir_base = "/myown_root_dir//gxy/code/UCTNet/UCTNet/nnUNet_trained_models"
```

Do you happen to know how I can solve the error of FileNotFoundError: [Errno 2] No such file or '/mnt/storage/ji/systematic_review/UCTNet/home/gxy/data_pro/nnUNet_preprocessed/Task027_ACDC/nnUNetPlansv2.1_plans_2D.pkl'

For your reference, my ACDC dataset structure is like below.
<img width="280" alt="Screenshot 2024-09-28 at 5 43 54 PM" src="https://github.com/user-attachments/assets/701a19dd-95ee-427f-816d-cdc23e877a1c">

Thank you.

**Comment by innocence0206** [comment]
Hi~
I'm sorry for missing a step. After processing the data with the command  `UCTNet_ACDC -dataset_path DATASET_PATH`
please execute `nnUNet_plan_and_preprocess -t 027 --verify_dataset_integrity` to create the training plans include nnUNetPlansv2.1_plans_2D.pkl.
If you still have any problem, feel free to let me know.

**Comment by greenyjwk** [comment]
Hello, 

Thank you so much for your prompt response. I could create the `'../home/gxy/data_pro/nnUNet_preprocessed/Task027_ACDC/nnUNetPlansv2.1_plans_2D.pkl'` file with the command you provided.

Thank you so much!
