### ISSUE TITLE
Running UCTNetTrainer.py

### ISSUE THREAD

**Issue by greenyjwk** [innocence0206/UCTNet#4]
In the file UCTNetTrainer.py

line 250-254, There are params and FLOPs print statements. Would you please provide the parameters size and FLOPs after running the UCTNetTrainer.py script file? I have been trying to run the model, but there are some issues so I would like to ask if you can provide those two values. 

Thank you.

**Comment by innocence0206** [comment]
```
if self.count_params:
        # input = torch.randn(1, 1, 48, 192, 192).cuda()
        # label = torch.randn(1, 1, 48, 192, 192).cuda()
        input = torch.randn(1, 1, 256, 224).cuda()
        label = torch.randn(1, 1, 256, 224).cuda()
        macs, params = profile(self.network.cuda(), inputs=(input, label, True))
        macs, params = clever_format([macs, params], "%.3f")
        print(f"Flops: {int(macs)/2}  params:{params}")
```
You can manually set `self.count_params` to `True` to conveniently count the parameter size and FLOPs. UCTNet accepts (x, tar, is_infer) as inputs, so please generate them based on the dataset's data size.

**Comment by greenyjwk** [comment]
Thank you so much!! It worked.
